### ISSUE TITLE
Extension doesn't autostart

### ISSUE THREAD

**Issue by famouzkk** [hedgieinsocks/dejaview#1]
Dejaview doesn't start automatically. I need to open the panel (this on the right upper corner), disable it, and then enable it again. I would like it to autostart.

**Comment by hedgieinsocks** [comment]
Hi there! 

1. Do you want the timer to go live automatically from the start whenever you log into your gnome session (e.g. after boot or unlock)? 

2. Is the extension pill in the quick settings enabled for you after you log in or unlock the screen?

The extension is supposed to be disabled by gnome 43-44 whenever your screen is locked. And this should disable the pill button in the  quick settings menu. And it works just like that for me. If your pill is enabled after login or unlock and you have to turn it off and then turn it on to launch the timer loop, then something is wrong. Please reproduce it on a fresh boot and if the issue is there, please provide me with more details on your setup.

**Comment by famouzkk** [comment]
1. Yes
2. Yes, the extension pill is enabled but it's not working. I need to disable and enable it again as you said. Tried rebooting many times.

I gonna try disabling other extensions and see if it helps. I didn't tried before because I thought that it is extension bug (or it is default behavior). I'm on Artix Linux, gnome-shell 1:44.3-1.

**Comment by famouzkk** [comment]
Disabling other extension didn't helped. What details of my setup you want to know?

**Comment by hedgieinsocks** [comment]
Thank you for your reply and for the check. The line that disables the pill in the quick settings is [here](https://github.com/hedgieinsocks/dejaview/blob/1377cb2c582b6315939c1809001a22fb877802f1/extension.js#L248). 

And if your pill is still enabled on unlock/login, it means that it did not get disabled on logout/lock. Perhaps your distro closes the gnome session incorrectly and abruptly and the extension has no chance to run disable() function. At least this is the only idea I have for now. 

Am I right that this weird thing happens on both login and unlock after sleep, or only on login? 

As for the option to auto-start the timer on login, I will consider it.

**Comment by famouzkk** [comment]
When going to sleep, timer doesn't stop, it looks like its working in background somehow, or calculate time on wake up. On logout or computer reboot the extension pill is blue but no timer or reminders.

**Comment by hedgieinsocks** [comment]
I see, then it does look distro-related since gnome 43-44 on wayland is supposed to call disable() on every extension at logout or screen lock. If the extension is not fully disabled on screen lock, then something is not right. Maybe you are not using wayland and using legacy x11 instead?

**Comment by famouzkk** [comment]
I'm for sure on Wayland.

**Comment by hedgieinsocks** [comment]
I have added an auto-start option to the extension settings in the latest [commit](https://github.com/hedgieinsocks/dejaview/commit/ab6cd8219a8f2b21bd4996086494dd7f367d1190) and submitted the new extension version to [EGO](https://extensions.gnome.org/extension/5850/dejaview/), so the update should become available in one of the upcoming days if it gets accepted. As for the bug you are facing, I think it is related to https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2621 but I have no idea why I don't experience it and you do. Hopefully, the auto-start feature kinda works around this issue.
